name: Your New Jekyll Site

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
source: _source
destination: _deploy
plugins: _plugins
timezone: America/Chicago
markdown: redcarpet
pygments: true
